name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install platformio
      - run: pio run
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/bluepill_f103c8/firmware.elf
